import {Component, ElementRef, EventEmitter, Output, ViewChild} from '@angular/core';
import {CommonModule} from "@angular/common";
import {AppComponent} from "../app.component";

@Component({
  selector: 'app-input-button-unit',
  standalone: true,
  imports: [CommonModule, AppComponent],
  templateUrl: './input-button-unit.component.html',
  styleUrl: './input-button-unit.component.scss'
})
export class InputButtonUnitComponent {
  title = 'Hello World';
  test = 'tes123';

  @Output() submit:EventEmitter<string> = new EventEmitter<string>();
  @ViewChild('inputElementRef') inputElement!: ElementRef;

  constructor() {
    this.title = 'I Love Angular';
    // this.changeTitle('My first Angular App');
  }

  changeTitle(newTitle: string): void {
    this.submit.emit(newTitle);
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  getInputValue(event: Event): string {
    return (event.target as HTMLInputElement).value;
  }

  submitValue(newTitle: string): void {
    this.submit.emit(newTitle);
    this.clearInput();
  }

  clearInput(): void {
    this.inputElement.nativeElement.value = '';
  }
}
