import {Component, OnInit} from '@angular/core';
import {CommonModule} from "@angular/common";
import {AppComponent} from "../app.component";

@Component({
  selector: 'app-input-button-unit',
  standalone: true,
  imports: [CommonModule, AppComponent],
  templateUrl: './input-button-unit.component.html',
  styleUrl: './input-button-unit.component.scss'
})
export class InputButtonUnitComponent {
  title = 'Hello World';
  test = 'tes123';

  constructor() {
    this.title = 'I Love Angular';
    this.changeTitle('My first Angular App');

    setTimeout(() => {
      this.title = 'This is not the title you are looking for';
    }, 3000);
  }

  changeTitle(newTitle: string): void{
    this.title = newTitle;
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  getInputValue(event: Event): string {
    return (event.target as HTMLInputElement).value;
  }
}
